# Generated by Django 3.2.6 on 2021-09-01 06:40

from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import need_gas_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('need_gas_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', enumfields.fields.EnumField(enum=need_gas_app.models.ServiceStates, max_length=15)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='need_gas_app.client')),
            ],
        ),
    ]
