# Generated by Django 3.2.6 on 2021-09-01 08:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("need_gas_app", "0002_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="created_time",
            field=models.DateField(
                default=datetime.datetime(2021, 9, 1, 3, 8, 28, 431708)
            ),
        ),
    ]
