# Generated by Django 3.2.6 on 2021-09-01 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('need_gas_app', '0003_service_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='created_time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
