# Generated by Django 3.2.6 on 2021-09-02 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('need_gas_app', '0004_alter_service_created_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='client_id',
        ),
        migrations.AddField(
            model_name='service',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='need_gas_app.client'),
            preserve_default=False,
        ),
    ]
