# Generated by Django 3.2.6 on 2021-09-02 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("need_gas_app", "0006_auto_20210901_2224"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="service",
            name="created_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="service",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
